
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true
  logging:
    level.org.hibernate:
          type: TRACE
          SQL: DEBUG
  output.ansi.enabled: always